
class Exception4 {

    void method() throws Exception {

    }
}